development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  # redistogo_url: redis://redistogo:dd9d85864618707c2a555e878c410921@grouper.redistogo.com:10888
  # url: redis://redistogo:dd9d85864618707c2a555e878c410921@grouper.redistogo.com:10888